source 'https://rubygems.org'

gem 'rails', '5.2.2'
gem 'bootsnap'
gem 'pg', '~> 0.15'
gem 'mysql2'
gem 'foreman'
gem 'bootstrap-sass', '~> 3.3.7' #, github: 'twbs/bootstrap-sass', branch: 'master'
gem 'sass-rails', '>= 3.2'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'rails-i18n', '~> 4.0.0' # For 4.0.x
gem 'simple_form'
gem 'unicorn'
gem 'unicorn-rails'
gem 'puma'
gem 'test-unit'
gem 'font-awesome-rails'
gem 'figaro'
gem 'haml-rails'
gem 'devise'
gem 'mini_magick'
gem 'refile', require: 'refile/rails', github: 'refile/refile'
gem 'refile-mini_magick', github: 'refile/refile-mini_magick'
gem 'sinatra'
gem 'trix-rails', require: 'trix'
# gem 'fog', require: 'fog/rackspace'
gem 'high_voltage'
gem 'koala'
gem 'mechanize'
gem 'twitter'
gem 'pry'
gem 'minitest'
gem 'will_paginate', '~> 3.0.5'
gem 'bootstrap-will_paginate'
gem 'acts-as-taggable-on'
gem 'chosen-rails'
gem 'pg_search'
gem 'sidekiq'
group :development, :test do
  gem 'byebug'
end

group :test do
  gem 'faker'
  gem 'guard'
end
group :development do
  # gem 'web-console', '~> 2.0'
  gem 'capistrano'
  gem 'capistrano-bundler'
  gem 'capistrano-rails', '~> 1.1.0'
  gem 'capistrano-rails-console'
  gem 'capistrano-rbenv'
  gem "capistrano-sidekiq"
end
