default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: sedmodnev_development

test:
  <<: *default
  database: sedmodnev_test


production:
  <<: *default
  database: sedmodnev_production
  username: sedem
  password: <%= ENV['SEDMODNEV_DATABASE_PASSWORD'] %>
