# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c1a3e95b65aa7cb81706d2010d366380b26a4591469a5491ba7eea35f362ce5a8f805de160c7e418c9cc7f8f906f4f46be9e2b6e3d137fdd93ce4db73442603

test:
  secret_key_base: 06e631876b0bc4f1c9ead51f61b6bcb57a3617ee1e7a48236d4f4c0f02dd0f890268cc6614e1999d17c8431c3173f316e0a1128bc37936f58a8f0937b9456528

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
